tests: reduce flakiness
freeCodeCamp/publish pull request #425
Opened 2024-02-04 11:51 UTC by Nirajn2311

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2024-02-05 10:18 UTC, ojeytonwilliams requested changes

2024-02-05 10:18 UTC, ojeytonwilliams commented on e2e/editor-drawer.spec.ts
> +    });
```suggestion
    await expect(saveNotificationTitle).toHaveText("Post has been updated.");
```
This seemed to work just fine for me. Was it necessary to have `useInnerText` on your machine?

2024-02-05 10:18 UTC, ojeytonwilliams commented on e2e/editor-drawer.spec.ts
> +    });
```suggestion
    await expect(saveNotificationTitle).toHaveText("Post has been updated.");
```

2024-02-05 10:18 UTC, ojeytonwilliams commented on e2e/editor-drawer.spec.ts
> +    });
```suggestion
    await expect(saveNotificationTitle).toHaveText("Post has been updated.");
```

2024-02-05 16:20 UTC, Nirajn2311 commented on e2e/editor-drawer.spec.ts
> +    });
Not exactly. Playwright dint work properly when I checked yesterday so I pushed them here to check them through actions. Lemme clean up and try the tests again.

2024-02-06 13:44 UTC, ojeytonwilliams approved these changes
Cheers, @Nirajn2311, this LGTM :+1:

2024-02-06 14:05 UTC, merged