Add docker-compose for development environment
freeCodeCamp/publish pull request #76
Opened 2023-08-07 15:20 UTC by sidemt

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #67

I referenced https://docs.strapi.io/dev-docs/installation/docker#optional-docker-compose for the example of docker-compose.yml.

2023-08-08 14:12 UTC, raisedadead requested changes

2023-08-08 15:45 UTC, raisedadead commented on publish-backend/docker-compose.yml
> +    image: mysql:8.0
I would use whatever they recommend.

2023-08-10 18:41 UTC, raisedadead requested changes
Other general nitpick is the numbering scheme, why use only `1.`?? 😅

2023-08-10 18:41 UTC, raisedadead commented on docs/README.md
> -1. Run `npm install`
`npm install` is still required if you want to run things outside the docker context like the `npm run cs import` command later.

2023-08-10 18:41 UTC, raisedadead commented on docs/README.md
>  1. Run `npm run cs import` to import config from `config/sync/*` files into
Add a step to open a separate terminal to run these commands. Someone might kill their compose session thinking it is OK.

2023-08-10 18:46 UTC, raisedadead commented on docs/README.md
>  1. Run `npm run cs import` to import config from `config/sync/*` files into
Also, I think registering the first user is essential before running any scripts, those instructions should be included.

2023-08-11 07:52 UTC, zairahira commented on docs/README.md
>  1. Run `npm run cs import` to import config from `config/sync/*` files into
```suggestion
1. In a separate terminal, run `npm install`. After that, run `npm run cs import` to import config from `config/sync/*` files into the database
```

2023-08-11 08:16 UTC, raisedadead commented
> Hey Mrugesh, this is a neat trick in Github markdown to get ordered numbers without worrying about the sequence :)

I am well aware of it 😅 - and it is an antipattern that we should not be following.

2023-08-11 08:17 UTC, raisedadead commented on docs/README.md
>  1. Run `npm run cs import` to import config from `config/sync/*` files into
Actually not that straight. The point of setting up compose is to be able to avoid setting up Node.js and its tool chain all together.

2023-08-13 16:58 UTC, raisedadead reviewed
Assuming the current vision for setup:

1. Developer needs a Node.js Environment - Involves installing it natively
2. Developer can spin the DB and Strapi Backend with Docker. We provide the compose setup for this.
3. Developer uses separate terminals to do three basic things:
	- Startup the Strapi Backend
	- Startup the Nextjs Frontend local server
	- Run ad-hoc commands on the backend, like populating the DB, etc. 

Could you consider rearranging the steps for this? 

Not a concern for this PR, the instructions are married to the folder structure. That should not be the case, as we refactor and rearrange things, it should be a good idea to break away from the naming. 

See #81

2023-08-14 19:19 UTC, raisedadead approved these changes

2023-08-14 19:20 UTC, merged