feat: get linting working
freeCodeCamp/publish pull request #82
Opened 2023-08-11 09:26 UTC by Sembauke

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2023-08-11 10:53 UTC, Nirajn2311 commented on publish-frontend/package.json
> +  },
Lets keep lint staged config in its own config file

2023-08-11 10:54 UTC, Nirajn2311 commented on publish-frontend/.eslintrc.json
> +}
This file is mixed with spaces and tabs

2023-08-11 10:54 UTC, Nirajn2311 commented on package.json
> +  },
Keep `husky` only in devDeps

2023-08-11 11:46 UTC, ojeytonwilliams requested changes
Any linting really should run in CI. If not, we won't realise there are issues.

2023-08-11 11:46 UTC, ojeytonwilliams commented on publish-frontend/.eslintrc.json
> +    ],
This looks like it's prettier's responsibility. The only thing the eslint config should do with respect to formatting is ignore it.

2023-08-11 11:46 UTC, ojeytonwilliams commented on publish-frontend/.lintstagedrc
> +  "**/*.{js,jsx,ts,tsx}": ["eslint", "prettier --fix"]
prettier needs installing

2023-08-16 07:46 UTC, ojeytonwilliams requested changes
Looking good, @Sembauke, just a couple of minor things:

2023-08-16 07:46 UTC, ojeytonwilliams commented on publish-frontend/src/lib/users.js
> +console.log(doubleqouted);
```suggestion
```

2023-08-16 07:46 UTC, ojeytonwilliams commented on publish-frontend/src/pages/articles/preview/[articleId].js
> +  const [_content, setContent] = useState('');
```suggestion
```
Since `setContent` isn't meaningfully used, I'd get rid of it (it's also on line 22).

2023-08-17 07:08 UTC, ojeytonwilliams approved these changes

2023-08-17 07:44 UTC, Nirajn2311 submitted a review, later dismissed
As we've got ESLint and Prettier in this PR, might as well get EditorConfig in here also. The same config used in main repo can be used here.

2023-08-17 08:33 UTC, Nirajn2311 approved these changes

2023-08-17 08:34 UTC, merged